### ISSUE TITLE
Add custom SPI

### ISSUE THREAD

**Issue by MatteoGioioso** [bitnami/bitnami-docker-keycloak#10]
**Description**

I am trying to use this image with custom authenticators, however it does not seems to work as expected.

This is the actual setup working with a local keycloak version:

1. I will build my custom SPI jar
2. create `module.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="com.example.mymodule">
    <resources>
        <resource-root path="mymodule-1.0-SNAPSHOT.jar"/>
    </resources>
    <dependencies>
        <module name="org.keycloak.keycloak-core"/>
        <module name="org.keycloak.keycloak-server-spi"/>
    </dependencies>
</module>

```
3. Create a custom `standalone-ha.xml`, I just copy the default provided by the keycloak code and add my custom providers:
```
<subsystem xmlns="urn:jboss:domain:keycloak-server:1.1">
            <web-context>auth</web-context>
            <providers>
                <provider>classpath:${jboss.home.dir}/providers/*</provider>
                <provider>classpath:${jboss.home.dir}/modules/mymodule/*</provider>
            </providers>
```
4. Copy those files inside the image

```
FROM bitnami/keycloak:13.0.1 AS final

COPY --from=stage-02 /app/target/mymodule-1.0-SNAPSHOT.jar /opt/bitnami/keycloak/modules/mymodule/
COPY myproject/module.xml /opt/bitnami/keycloak/modules/doctorworld/
#COPY myproject/standalone-ha.xml /opt/bitnami/keycloak/standalone/configuration/

```
5. Start my docker compose:

```
version: "3.0"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
  keycloak:
    build: .
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgresql
    volumes:
      - $PWD/myproject/standalone-ha.xml:/bitnami/keycloak/configuration/standalone-ha.xml

```

### Different scenarios

- With the volume mounted it will give me an error when I try to login: `You need local access to create the initial admin user.`
- If I try to simply copy the `standalone-ha.xml` into the image, somehow it will override it: `COPY myproject/standalone-ha.xml /opt/bitnami/keycloak/standalone/configuration/` and my providers won't appear.

What am I doing wrong?

**NOTE: all this configuration is working without using this image and simply starting a keycloak server with `bin/standalone.sh --server-config=standalone-ha.xml ` **
