### ISSUE TITLE
Custom-Theme 

### ISSUE THREAD

**Issue by patrik-upspot** [bitnami/bitnami-docker-keycloak#20]
I have some truble to get my custom theme with bitnami helm into my kubernetes cluster.
I dont know the correct way of configuration.

Thats my helm.yml

```
---
  global: 
    storageClass: "longhorn"
  ingress: 
    certManager: true
    enabled: true
    hostname: "keycloak.upspot.de"
    tls: true
  postgresql: 
    enabled: true
    persistence: 
      enabled: true
    postgresqlPassword: "***"
    postgresqlUsername: "***"
  proxyAddressForwarding: true
  service:
    type: "ClusterIP"
  initdbScriptsConfigMap: "keycloak-db-scripts"
  auth:
    adminPassword: "36EekotkSd"
        
  extraInitContainers:
    - name: theme-provider
      image: ghcr.io/upspot/keycloak-upspot/image:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /upspot/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
          
  extraVolumeMounts:
    - name: theme
      mountPath: /opt/bitnami/keycloak/themes/upspot

  extraVolumes:
    - name: theme
      emptyDir: {}
```

How should i create the "keycloak-upspot" image?

**Comment by marcosbc** [comment]
Hi @patrik-upspot, note that there is no need for you to create a container image just to copy the theme. For instance, you could clone it directly via git:

```yaml
  extraInitContainers:
    - name: theme-provider
      image: bitnami/git:2.33.0-debian-10-r8
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          . /opt/bitnami/scripts/git/entrypoint.sh
          git clone https://github.com/AUTHOR/REPO /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
```

or downloading it from a URL:

```yaml
  extraInitContainers:
    - name: theme-provider
      image: bitnami/git:2.33.0-debian-10-r8
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          . /opt/bitnami/scripts/git/entrypoint.sh
          curl https://domain.com/path/to/theme.tar.gz | tar xz -C /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
```

There are also many different ways for you to do them. I'd suggest you try different approaches until you find one that works the best.

**Comment by patrik-upspot** [comment]
Thanks for your help, bit i have one more problem. The Repository of the theme is private. So this solution does not work.

My yml looks like this:

```
---
  global: 
    storageClass: "longhorn"
  ingress: 
    certManager: true
    enabled: true
    hostname: "***"
    tls: true
  postgresql: 
    enabled: true
    persistence: 
      enabled: true
    postgresqlPassword: "***"
    postgresqlUsername: "***"
  proxyAddressForwarding: true
  service:
    type: "ClusterIP"
  initdbScriptsConfigMap: "keycloak-db-scripts"
  auth:
    adminPassword: "***"
        
  extraInitContainers:
    - name: theme-provider
      image: bitnami/git:2.33.0-debian-10-r8
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          . /opt/bitnami/scripts/git/entrypoint.sh
          git clone https://github.com/upspot/keycloak-upspot /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
          
  extraVolumeMounts:
    - name: theme
      mountPath: /opt/bitnami/keycloak/themes/upspot

  extraVolumes:
    - name: theme
      emptyDir: {}
```

The repository credentials are saved at the rancher. The Dockerimages can be downloaded.
