### ISSUE TITLE
Unable to access admin console

### ISSUE THREAD

**Issue by sunflowerno0b** [bitnami/bitnami-docker-keycloak#34]
**Description**

Fresh installation within my docker-compose file. I can access my keycloak service online, but when I attempt to access the admin console, the next page that loads is totally blank.

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]
----
1: go to my URL (keycloak-staging XXXX) 
2: i see the keycloak interface, welcoming me to keycloak
3: i attempt to access the admin console 
4: the page loads only to blank- this is the trailing portion of the url: /auth/admin/master/console/

**Describe the results you received:**
I receive a white screen.

**Describe the results you expected:**

I wanted to enter the admin console to start creating realms and users.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 20.10.8, build 3967b7d
```

- Output of `docker info`:

```
(Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 17
  Running: 11
  Paused: 0
  Stopped: 6
 Images: 13
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1021-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.688GiB
 Name: ip-172-31-43-147
 ID: HRHT:Q3BP:YHMS:JXEV:IAIY:XR7R:4SLY:MBGG:L3LF:M76W:KDAX:D4RC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using AWS.

**Comment by javsalgar** [comment]
Hi,

Could you provide your docker-compose file that triggers the issue? We test this solution with the regular docker-compose file and find no issues.

**Comment by sunflowerno0b** [comment]
Hi,

thanks for getting back. including the two services I have in my docker-compose file. If you need the whole thing (its rather long) let me know.
```
postgres-keycloak:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgres-keycloak-data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:15
    depends_on:
      - postgres-keycloak
    environment:
      #ADMIN_CREDENTIALS
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=systems
      - KEYCLOAK_ADMIN_PASSWORD=[PASSWORD LIVES HERE]
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
      - KEYCLOAK_DATABASE_HOST=postgres-keycloak
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=[PASSWORD LIVES HERE]
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_JDBC_PARAMS=sslmode=verify-full&connectTimeout=30000
```

**Comment by javsalgar** [comment]
Hi,

Could you share the full docker-compose file? We're having problems reproducing the issue. Do you have any github repository with an example that triggers the issue?

**Comment by sunflowerno0b** [comment]
I don't have a repo, this is living on my server. Including the full docker compose - note I am trying to install it to work with service aleph

```
version: "3.2"

services:
  postgres:
    image: postgres:10.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aleph
      #POSTGRES_PASSWORD: 
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph

  elasticsearch:
    image: ghcr.io/alephdata/aleph-elasticsearch:0dda9342826b9a0ae18c92b5d06d7c5b33d50627
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "3600", "10"]
    volumes:
      - redis-data:/data

  postgres-keycloak:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgres-keycloak-data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:15
    depends_on:
      - postgres-keycloak
    environment:
      #ADMIN_CREDENTIALS
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=systems
      - KEYCLOAK_ADMIN_PASSWORD=
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
      - KEYCLOAK_DATABASE_HOST=postgres-keycloak
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=test
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_JDBC_PARAMS=sslmode=verify-full&connectTimeout=30000
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Washington
      - URL=pulitzercenter.org
      - SUBDOMAINS=rindata-staging,keycloak-staging
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - swag-data:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  convert-document:
    image: ghcr.io/alephdata/convert-document:3.14.4
    read_only: true
    restart: on-failure
    user: app
    tmpfs: /tmp

  ingest-file:
    image: ghcr.io/alephdata/ingest-file:3.14.4
    read_only: true
    restart: on-failure
    user: app
    tmpfs: /tmp

  ingest-file:
    image: ghcr.io/alephdata/ingest-file:3.14.4
    tmpfs:
      - /tmp:mode=777
    volumes:
      - archive-data:/data
    depends_on:
      - postgres
      - redis
      - convert-document
    restart: on-failure
    env_file:
      - aleph.env
  worker:
    image: alephdata/aleph:${ALEPH_TAG:-3.11.0}
    command: aleph worker
    restart: on-failure
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - ingest-file
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
    env_file:
      - aleph.env

  shell:
   image: alephdata/aleph:${ALEPH_TAG:-3.11.0}
    command: /bin/bash
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - ingest-file
      - worker
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
      - "./mappings:/aleph/mappings"
      - "~:/host"
    env_file:
      - aleph.env

  api:
    image: alephdata/aleph:${ALEPH_TAG:-3.11.0}
    command: gunicorn -w 6 -b 0.0.0.0:8000 --log-level debug --log-file - aleph.wsgi:app
    expose:
      - 8000
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - worker
      - ingest-file
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
    env_file:
      - aleph.env

  ui:
    image: alephdata/aleph-ui-production:${ALEPH_TAG:-3.11.0}
    depends_on:
      - api
    ports:
      - "8080:8080"
      volumes:
  archive-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/archive-data
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/postgres-data
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/redis-data
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/elasticsearch-data

  swag-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/swag

  postgres-keycloak-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/postgres-keycloak
```

**Comment by javsalgar** [comment]
Hi,

It seems to me that this will be difficult to reproduce on our side. Does the same issue happen without ceph and using regular docker volumes?

**Comment by sunflowerno0b** [comment]
thank you, if you see in the docker compose, there is no ceph - the driver is local on a host machine. i've pulled an update for keycloak:15 but the problem persists. running a network inspector I found that the output appears that keycloak is wanting to pull http but my instance of keycloak is https - attaching a screen shot.
![Screen Shot 2021-12-20 at 9 27 40 AM](https://user-images.githubusercontent.com/68705196/146800005-39c18066-94dc-4e39-acd4-0dab564e644e.png)

any idea on how to fix so that it goes HTTPS? this might solve the issue

**Comment by javsalgar** [comment]
This ticket is related to the chart but it could be useful for the HTTPS issue

https://github.com/bitnami/charts/issues/6940

**Comment by brsolomon-deloitte** [comment]
See https://github.com/bitnami/charts/issues/6940#issuecomment-1008903484 for some additional steps that may be required if behind a reverse proxy.

**Comment by k2r79** [comment]
I had a similar issue with Keycloak behind a Traefik reverse proxy that redirects HTTP to HTTPS, the solution was to :
- add the `PROXY_ADDRESS_FORWARDING=true` environment variable to my Keycloak container
- add `X-Forwarded-*` headers which is done like below in Traefik (https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers)

```yaml
entryPoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    forwardedHeaders:
      insecure: true
```
