### ISSUE TITLE
using docker-compose, admin console is blank page, "KEYCLOAK_PROXY_ADDRESS_FORWARDING=true" not working?

### ISSUE THREAD

**Issue by lknite** [bitnami/bitnami-docker-keycloak#50]
### Name and Version

bitnami/keycloak:latest

### What steps will reproduce the bug?

Follow steps on docker hub page for a basic setup, using docker-compose up:
https://hub.docker.com/r/bitnami/keycloak/

Then setup haproxy as a reverse proxy to handle the tls termination:
https://www.haproxy.com/blog/haproxy-ssl-termination/

Add environment variables to docker-compose to setup tls:
```
  keycloak:
    restart: always
    image: docker.io/bitnami/keycloak:16
    environment:
      - KEYCLOAK_PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_ENABLE_TLS=true
      - KEYCLOAK_TLS_KEYSTORE_FILE=/opt/bitnami/keycloak/certs/keycloak-0.keystore.jks
      - KEYCLOAK_TLS_TRUSTSTORE_FILE=/opt/bitnami/keycloak/certs/keycloak.truststore.jks
      - KEYCLOAK_TLS_KEYSTORE_PASSWORD=changeme
      - KEYCLOAK_TLS_TRUSTSTORE_PASSWORD=changeme
    volumes:
      - '/pathto/keycloak/certs:/opt/bitnami/keycloak/certs'
```

### What is the expected behavior?

working keycloak setup with valid certificates

### What do you see instead?

Everything appears to be working initially, certificates are valid and we are presented with initial screen.  There is an administration console to click on, however, upon being clicked a blank page is displayed.

**Comment by lknite** [comment]
/etc/haproxy/haproxy.cfg (the last few lines, otherwise default configuration):
```
# accept both 80 and 443, redirecting 80 to 443 automatically
frontend itskeycloak.ics.idaho.gov
    bind 0.0.0.0:80 ssl crt /etc/ssl/certs/keycloak.mydomain.pem
    bind 0.0.0.0:443 ssl crt /etc/ssl/certs/keycloak.mydomain.pem
    http-request redirect scheme https unless { ssl_fc }
    default_backend             keycloak

backend keycloak
    balance     roundrobin
    server  app1 127.0.0.1:8080 verify none
```

docker-compose.yml:
```
version: '2'
services:
  postgresql:
    restart: always
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    restart: always
    image: docker.io/bitnami/keycloak:16
    environment:
      - KEYCLOAK_PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_ENABLE_TLS=true
      - KEYCLOAK_TLS_KEYSTORE_FILE=/opt/bitnami/keycloak/certs/keycloak-0.keystore.jks
      - KEYCLOAK_TLS_TRUSTSTORE_FILE=/opt/bitnami/keycloak/certs/keycloak.truststore.jks
      - KEYCLOAK_TLS_KEYSTORE_PASSWORD=changeme
      - KEYCLOAK_TLS_TRUSTSTORE_PASSWORD=changeme
    volumes:
      - '/pathto/keycloak/certs:/opt/bitnami/keycloak/certs'
    depends_on:
      - postgresql
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
    driver: local
```
