### ISSUE TITLE
Admin Console access, use of http js request instead of https requet then mixed content error in Firefox

### ISSUE THREAD

**Issue by rv2931** [bitnami/bitnami-docker-keycloak#55]
### Name and Version

bitnami/keycloak:16

### What steps will reproduce the bug?

I'm running Debian 10, using bitnami/keycloak:16 with apache proxy

- Here you can find my apache proxy file

```
<VirtualHost *:443>
    ServerName mysite.com
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/mysite.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mysite.com/privkey.pem

    RewriteEngine on
    RewriteRule "^$" "/" [R,L]
    ProxyRequests off

    <Location "/">
      RequestHeader set X-Forwarded-Proto 'https'
      ProxyPreserveHost On
      ProxyPass http://127.0.0.1:8081/
      ProxyPassReverse http://127.0.0.1:8081/
    </Location>
</VirtualHost>
```
- Here the compose file after retrieving it from github

```
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-keycloak/master/docker-compose.yml
```
```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
        #volumes:
        #- 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - postgresql
    ports:
      - "8081:8080"

        #volumes:
        #postgresql_data:
        #driver: local
keycloak@vps697378:~$ more docker-compose.yml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
        #volumes:
        #- 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - postgresql
    ports:
      - "8081:8080"

        #volumes:
        #postgresql_data:
        #driver: local
```
- then running docker-compose up

- when accessing https://mysite.com the welcome page of keycloak is OK
- when I try to access the admin console page I get an empy white page
- in the web console of firefox I get some errors
- 

```
Échec du chargement pour l’élément <script> dont la source est « http://mysite.com/auth/js/keycloak.js?version=bxlvg ». [console](https://mysite.com/auth/admin/master/console/):49:1

jQuery.Deferred exception: Keycloak is not defined @https://mysite.com/auth/resources/bxlvg/admin/keycloak/js/app.js:14:24
 undefined [jquery.min.js:2:31560](https://mysite.com/auth/resources/bxlvg/common/keycloak/node_modules/jquery/dist/jquery.min.js)
Uncaught ReferenceError: Keycloak is not defined
    <anonymous> https://mysite.com/auth/resources/bxlvg/admin/keycloak/js/app.js:14
    jQuery 13

```

So first error is due to the fact that despite the fact that first access url is https://mysite.com, keycloak try to load app.js from http://mysite.com/..../app.js instead of https://mysite.com/..../app.js
This causes a mixed content security error, then app.js load fails then Keycloak javascript objet is unknown and so the console access wbe page is not loaded

### What is the expected behavior?

All static resources, overall app.js should be using https protocol when the access page is https. This to avoid mixed content security error

### What do you see instead?

Empty page when trying to access admin console web page

### Additional information

Maybe it is due to apache misconfiguration but I don't see the error
