### ISSUE TITLE
I'm not able to enable plugins using env KEYCLOAK_EXTRA_ARGS

### ISSUE THREAD

**Issue by mancausoft** [bitnami/bitnami-docker-keycloak#58]
### Name and Version

public.ecr.aws/bitnami/keycloak@sha256:9daa8da171ff4b27857cee471461e0eebf40fdbbd423f8a18323e1e9081b26d3

### What steps will reproduce the bug?

Run the docker with enviroment KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled

### What is the expected behavior?

```$ ps -efww
UID        PID  PPID  C STIME TTY          TIME CMD
keycloak     1     0  1 13:50 ?        00:00:29 java -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dkc.home.dir=/opt/bitnami/keycloak/bin/../ -Djboss.server.config.dir=/opt/bitnami/keycloak/bin/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp /opt/bitnami/keycloak/bin/../lib/quarkus-run.jar io.quarkus.bootstrap.runner.QuarkusEntryPoint -cf /opt/bitnami/keycloak/conf/keycloak.conf --profile=dev start-dev --auto-build -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
keycloak   833     0  0 14:23 pts/0    00:00:00 /bin/bash
```
### What do you see instead?

```$ ps -efww
UID        PID  PPID  C STIME TTY          TIME CMD
keycloak     1     0  1 13:50 ?        00:00:29 java -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dkc.home.dir=/opt/bitnami/keycloak/bin/../ -Djboss.server.config.dir=/opt/bitnami/keycloak/bin/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp /opt/bitnami/keycloak/bin/../lib/quarkus-run.jar io.quarkus.bootstrap.runner.QuarkusEntryPoint -cf /opt/bitnami/keycloak/conf/keycloak.conf --profile=dev start-dev --auto-build
keycloak   833     0  0 14:23 pts/0    00:00:00 /bin/bash
```
```
curl 'https://keycloak.develop.vitaminology.co/realms/DarekTests/protocol/openid-connect/token' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange&client_id=test&client_secret=(DELETED)&requested_token_type=urn:ietf:params:oauth:token-type:access_token'
{"error":"Feature not enabled"}
```

### Additional information

```$ env
KEYCLOAK_MANAGEMENT_USER=(removed)
KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
KEYCLOAK_ADMIN_PASSWORD=(deleted)
HOSTNAME=e7b18f080e11
JAVA_HOME=/opt/bitnami/java
KEYCLOAK_DATABASE_HOST=postgresql.develop
PWD=/
OS_FLAVOUR=debian-10
ECS_CONTAINER_METADATA_URI_V4=http://169.254.170.2/v4/c916f18d-c33a-4b20-a326-8a89cdb772c1
KEYCLOAK_PROXY_ADDRESS_FORWARDING=true
KEYCLOAK_ADMIN_USER=(deleted)
HOME=/
SHLVL=1
KEYCLOAK_DATABASE_PASSWORD=(deleted)
BITNAMI_APP_NAME=keycloak
APP_VERSION=17.0.1
KEYCLOAK_CREATE_ADMIN_USER=true
OS_NAME=linux
PATH=/opt/bitnami/common/bin:/opt/bitnami/java/bin:/opt/bitnami/keycloak/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OS_ARCH=amd64
_=/usr/bin/env
```

I understand wrong thjis enviroment variable o it's a bug?

**Comment by javsalgar** [comment]
Hi,

Could you share a docker-compose.yaml where you see the bug?

**Comment by mancausoft** [comment]
I'm using it on ECS, here the task-definition:
```
  {
    "name": "keycloak",
    "image": "public.ecr.aws/bitnami/keycloak:latest",
    "cpu": 32,
    "memoryReservation": 512,
    "memory": 1024,
    "logConfiguration": {
      "logDriver": "json-file",
      "options": {
        "max-file": "5",
        "max-size": "20M"
      }
    },
    "secrets": [
      {
        "name": "KEYCLOAK_DATABASE_PASSWORD",
        "valueFrom": "${secrets_vault}:${environment}_KEYCLOAK_DATABASE_PASSWORD::"
      },
      {
        "name": "KEYCLOAK_ADMIN_PASSWORD",
        "valueFrom": "${secrets_vault}:${environment}_KEYCLOAK_ADMIN_PASSWORD::"
      },
      {
        "name": "KEYCLOAK_MANAGEMENT_USER",
        "valueFrom": "${secrets_vault}:${environment}_KEYCLOAK_MANAGEMENT_USER::"
      }

    ],
    "environment": [
      {
        "name": "KEYCLOAK_DATABASE_HOST",
        "value": "postgresql.${environment}"
      },
{
        "name": "KEYCLOAK_PROXY_ADDRESS_FORWARDING",
        "value": "true"
      },
      {
        "name": "KEYCLOAK_CREATE_ADMIN_USER",
        "value": "true"
      },
      {
        "name": "KEYCLOAK_EXTRA_ARGS",
        "value": " -Dkeycloak.profile=preview -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
      },
      {
        "name": "KEYCLOAK_ADMIN_USER",
        "value": "myadmin"
      }
    ],
    "portMappings": [
      {
        "containerPort": 8080,
        "protocol": "tcp"
      }
    ]
  }
]
    ```

**Comment by javsalgar** [comment]
Could you provide a similar docker-compose.yaml file that triggers the issue?

**Comment by AndreaVida** [comment]
I have a similar (and possibly related) issue when configuring [logging](https://www.keycloak.org/server/logging) using bitnami/keycloak Chart version 9.0.0 with following values:

```yaml
keycloakConfigCli:
    enabled: false
extraStartupArgs: "--log-console-output=json --spi-events-listener-jboss-logging-success-level=info --spi-events-listener-jboss-logging-error-level=warn"
```

My expectation would be to have those parameters appended after "kc.sh start" or "kc.sh start-dev" command at [run.sh#L26](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/18/debian-10/rootfs/opt/bitnami/scripts/keycloak/run.sh#L26), but it seems not to be the case (at least with dev mode):

```shell
keycloak       1  0.8  0.2 4112276 327888 ?      Ssl  May17  10:20 java -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dkc.home.dir=/opt/bitnami/keycloak/bin/../ -Djboss.server.config.dir=/opt/bitnami/keycloak/bin/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp /opt/bitnami/keycloak/bin/../lib/quarkus-run.jar io.quarkus.bootstrap.runner.QuarkusEntryPoint -cf /opt/bitnami/keycloak/conf/keycloak.conf --profile=dev start-dev --auto-build
```

**Comment by mancausoft** [comment]
```
 cat docker-compose.yml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:18
    depends_on:
      - postgresql
    environment:
      - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile=preview -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.script=enable

volumes:
  postgresql_data:
    driver: local
```

```keycloak@580c94d8e81a:/$ ps aux | more
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
keycloak       1  0.2  0.0   3736  2872 ?        Ss   09:22   0:00 /bin/bash /opt/bitnami/keycloak/bin/kc.sh -cf /opt/bitnami/keycloak/conf/keycloak.conf start-dev
keycloak     189  487  1.5 5568776 504276 ?      Sl   09:23   0:38 java -Dkc.config.rebuild-and-exit=true -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dkc.home.dir=/opt/bitnami/keycloa
k/bin/../ -Djboss.server.config.dir=/opt/bitnami/keycloak/bin/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp /opt/bitnami/keycloak/bin/../lib/quarkus-run.jar io.quarkus.boo
tstrap.runner.QuarkusEntryPoint -cf /opt/bitnami/keycloak/conf/keycloak.conf --profile=dev start-dev --auto-build```
