### ISSUE TITLE
KEYCLOCK_FRONTEND_URL -> KC_HOSTNAME

### ISSUE THREAD

**Issue by jack1902** [bitnami/bitnami-docker-keycloak#59]
### Name and Version

bitnami/keycloak 8.0.1

### What steps will reproduce the bug?

refer to: https://github.com/bitnami/charts/issues/10236

I'm just calling out an issue I have seen on the `env-var` as it is no longer `KEYCLOAK` but `KC_` to the underlying app

### What is the expected behavior?

frontend url to be set when `Quarkus` is initialised to show the value of the `HOSTNAME` env-var

### What do you see instead?

`<request>` when using `KEYCLOAK_FRONTEND_URL` which should really be `KC_HOSTNAME` per these docs:  https://www.keycloak.org/server/all-config?q=hostname

**Comment by Mauraza** [comment]
Hi @jack1902,

you are right, the `KEYCLOAK_FRONTEND_URL` does not update the hostname. We will fix and will update the thread when it's done.
For now, you can add the property `hostname` in `keycloack.conf`.

**Comment by jack1902** [comment]
i've gone down the `extraEnvVar

```yaml
extraEnvVars:
  # https://www.keycloak.org/server/hostname
  - name: KC_HOSTNAME
    value: "MY_DOMAIN"
  - name: KC_HOSTNAME_STRICT
    value: "true"
```
