### ISSUE TITLE
"sed: -e expression #1, char 176: unterminated `s' command" when using external database

### ISSUE THREAD

**Issue by cyclingwithelephants** [bitnami/bitnami-docker-keycloak#81]
### Name and Version

'docker.io/bitnami/keycloak:18.0.0-debian-10-r6'

### What steps will reproduce the bug?

- deploy cockroach db cluster with TLS enabled
- deploy keycloak using e.g. the below. I have determined that the DB config is causing the problem rather than ingress, but have included for completeness
```
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: <ArgoCD values omitted>
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 9.2.2
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: <omitted>
          annotations:
            external-dns.alpha.kubernetes.io/hostname: <omitted>
            cert-manager.io/cluster-issuer: letsencrypt-production
          tls: true
        postgresql:
          enabled: false
        externalDatabase:
          host: cockroach-db-public.cockroach-db # svc_name.namespace
          port: 26257
          user: keycloak
          database: keycloak
          existingSecret: keycloak-db # a secret I populate with a 63 character alphanumeric password
          existingSecretPasswordKey: password
```
produces a crashLoopBackoff and the following logs

### What is the expected behavior?

I was expecting some kind of error in relation to not passing certificates for authentication with the database - perhaps this is indeed that?

### What do you see instead?

```
keycloak 00:24:59.84
keycloak 00:24:59.84 Welcome to the Bitnami keycloak container
keycloak 00:24:59.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-keycloak
keycloak 00:24:59.85 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-keycloak/issues
keycloak 00:24:59.85
keycloak 00:24:59.85 INFO  ==> ** Starting keycloak setup **
keycloak 00:24:59.87 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 00:24:59.89 INFO  ==> Trying to connect to PostgreSQL server cockroach-db-public.cockroach-db...
keycloak 00:24:59.90 INFO  ==> Found PostgreSQL server listening at cockroach-db-public.cockroach-db:26257
keycloak 00:24:59.91 INFO  ==> Configuring database settings
sed: -e expression #1, char 176: unterminated `s' command
```
