### ISSUE TITLE
keycloak-cache-init error while starting container

### ISSUE THREAD

**Issue by nureynisow** [bitnami/bitnami-docker-keycloak#82]
### Name and Version

bitnami/keycloak:18

### What steps will reproduce the bug?

Below my compoose file 
```yml 
services:
  postgres:
    image: "postgres:14.3"
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
    image: docker.io/bitnami/keycloak:18
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '6060:8080'
#    volumes:
#      - "./keycloak-themes:/opt/bitnami/keycloak/themes"
volumes:
  db:
```
I created database and user with this init  script : 

```sql

CREATE ROLE keycloak
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    PASSWORD 'keycloak';

CREATE DATABASE keycloak
    WITH OWNER keycloak;
```

```env
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres

KEYCLOAK_DATABASE_HOST=postgres
KEYCLOAK_DATABASE_PORT=5432
KEYCLOAK_DATABASE_NAME=keycloak
KEYCLOAK_DATABASE_USER=keycloak
KEYCLOAK_DATABASE_PASSWORD=keycloak
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=mkp
KEYCLOAK_HTTP_PORT=6060
```

### What is the expected behavior?

I expected to get my keycloak running on port 6060

### What do you see instead?

Below the log i'm getting :

```log 
keycloak 09:07:30.58 

keycloak 09:07:30.61 Welcome to the Bitnami keycloak container

keycloak 09:07:30.63 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-keycloak

keycloak 09:07:30.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-keycloak/issues

keycloak 09:07:30.68 

keycloak 09:07:30.70 INFO  ==> ** Starting keycloak setup **

keycloak 09:07:30.84 INFO  ==> Validating settings in KEYCLOAK_* env vars...

keycloak 09:07:31.01 INFO  ==> Trying to connect to PostgreSQL server postgres...

keycloak 09:07:31.14 INFO  ==> Found PostgreSQL server listening at postgres:5432

keycloak 09:07:31.18 INFO  ==> Configuring database settings

keycloak 09:08:26.89 INFO  ==> Enabling statistics

keycloak 09:08:27.01 INFO  ==> Configuring http settings

keycloak 09:08:27.26 INFO  ==> Configuring hostname settings

keycloak 09:08:27.35 INFO  ==> Configuring cache count

keycloak 09:08:27.43 INFO  ==> Configuring log level

keycloak 09:08:27.51 INFO  ==> Configuring proxy

keycloak 09:08:27.66 INFO  ==> ** keycloak setup finished! **

keycloak 09:08:27.80 INFO  ==> ** Starting keycloak **


Updating the configuration and installing your custom providers, if any. Please wait.

2022-06-06 09:08:54,165 WARN  [org.keycloak.services] (build-4) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice

2022-06-06 09:08:58,408 WARN  [org.keycloak.services] (build-4) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice

2022-06-06 09:09:24,983 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 45651ms

2022-06-06 09:09:41,843 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true

2022-06-06 09:09:46,992 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal

2022-06-06 09:09:47,114 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled

2022-06-06 09:09:47,185 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'

2022-06-06 09:09:48,122 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final

2022-06-06 09:09:48,566 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`

2022-06-06 09:09:48,567 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!

2022-06-06 09:09:48,972 ERROR [org.jgroups.protocols.UDP] (keycloak-cache-init) failed setting interface to /172.20.0.3: java.net.SocketException: Protocol not available (Error setting socket option)

2022-06-06 09:09:48,975 ERROR [org.jgroups.protocols.UDP] (keycloak-cache-init) failed setting interface to /172.20.0.3: java.net.SocketException: Protocol not available (Error setting socket option)

2022-06-06 09:09:49,384 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode

2022-06-06 09:09:49,387 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches

2022-06-06 09:09:49,389 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheException: Unable to start JGroups Channel

2022-06-06 09:09:49,389 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.commons.CacheException: Unable to start JGroups Channel

2022-06-06 09:09:49,390 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel

2022-06-06 09:09:49,391 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Protocol not available

2022-06-06 09:09:49,392 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.```

### Additional information

_No response_

**Comment by dgomezleon** [comment]
Hi @nureynisow ,

I can see you are using a custom postgresql image. I was able to make it work using bitnami/postgresql and these files:

.env:
```
#POSTGRES_USER=postgres
#POSTGRES_PASSWORD=postgres
#POSTGRES_DB=postgres
POSTGRESQL_USERNAME=bn_keycloak
POSTGRESQL_DATABASE=bitnami_keycloak
ALLOW_EMPTY_PASSWORD=yes

KEYCLOAK_DATABASE_HOST=postgres
KEYCLOAK_DATABASE_PORT=5432
KEYCLOAK_DATABASE_NAME=bitnami_keycloak
KEYCLOAK_DATABASE_USER=bn_keycloak

KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=mkp
KEYCLOAK_HTTP_PORT=8080
```
Note the `KEYCLOAK_HTTP_PORT`.

docker-compose.yaml
```
services:
  postgres:
    image: "docker.io/bitnami/postgresql:14"
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
    image: docker.io/bitnami/keycloak:18
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '6060:8080'
#    volumes:
#      - "./keycloak-themes:/opt/bitnami/keycloak/themes"
volumes:
  db:
```

I hope it helps
