### ISSUE TITLE
Setting the environment variable KEYCLOAK_JDBC_PARAMS has no effect

### ISSUE THREAD

**Issue by christianramcke** [bitnami/bitnami-docker-keycloak#89]
### Name and Version

bitnami / bitnami-docker-keycloak:18.0.2-debian-11-r2 release

### What steps will reproduce the bug?

**Environment:** 

* Docker 20.10.16
* Docker Compose 2.6.0
* PostgreSQL 14.2 (Ubuntu 14.2-1.pgdg18.04+1)

**Reproduce + Results:**

* Add environment parameter `KEYCLOAK_JDBC_PARAMS: connectTimeout=300`
* Start the container and login into keycloak admin console
* Under _Server info_ / _Providers_ check the connectionsJpa / databaseUrl of the quarkus provider
* The connectTimeout=300 property was not set
<img width="909" alt="2022-06-30 18_22_32-Keycloak Admin Console" src="https://user-images.githubusercontent.com/99256207/176728544-c3182506-0463-46f4-b51d-01b4d24e8cc9.png">

We tried more properties for the JDBC params (readOnly for example) and no one works.

### What is the expected behavior?

We expected the databaseUrl query parameters with adjusted values.
In this case the following databaseUrl:
```
jdbc:postgresql://bsc-keycloak-postgresql.service-keycloak:5432/keycloak_production?adaptiveFetch=false&adaptiveFetchMaximum=-1&adaptiveFetchMinimum=0&allowEncodingChanges=false&ApplicationName=PostgreSQL+JDBC+Driver&autosave=never&binaryTransfer=true&binaryTransferDisable=&binaryTransferEnable=&cancelSignalTimeout=10&cleanupSavepoints=false&connectTimeout=300&currentSchema=public&databaseMetadataCacheFields=65536&databaseMetadataCacheFieldsMiB=5&defaultRowFetchSize=0&disableColumnSanitiser=false&escapeSyntaxCallMode=select&gssEncMode=allow&gsslib=auto&hideUnprivilegedObjects=false&hostRecheckSeconds=10&jaasApplicationName=pgjdbc&jaasLogin=true&loadBalanceHosts=false&loginTimeout=0&logServerErrorDetail=true&logUnclosedConnections=false&preferQueryMode=extended&preparedStatementCacheQueries=256&preparedStatementCacheSizeMiB=5&prepareThreshold=5&quoteReturningIdentifiers=true&readOnly=false&readOnlyMode=transaction&receiveBufferSize=-1&reWriteBatchedInserts=false&sendBufferSize=-1&socketTimeout=0&sspiServiceClass=POSTGRES&targetServerType=any&tcpKeepAlive=false&tcpNoDelay=false&unknownLength=2147483647&useSpnego=false&xmlFactoryFactory=
```

connectTimeout is 300 here.

### What do you see instead?

But we get the following databaseUrl:
```
jdbc:postgresql://bsc-keycloak-postgresql.service-keycloak:5432/keycloak_production?adaptiveFetch=false&adaptiveFetchMaximum=-1&adaptiveFetchMinimum=0&allowEncodingChanges=false&ApplicationName=PostgreSQL+JDBC+Driver&autosave=never&binaryTransfer=true&binaryTransferDisable=&binaryTransferEnable=&cancelSignalTimeout=10&cleanupSavepoints=false&connectTimeout=10&currentSchema=public&databaseMetadataCacheFields=65536&databaseMetadataCacheFieldsMiB=5&defaultRowFetchSize=0&disableColumnSanitiser=false&escapeSyntaxCallMode=select&gssEncMode=allow&gsslib=auto&hideUnprivilegedObjects=false&hostRecheckSeconds=10&jaasApplicationName=pgjdbc&jaasLogin=true&loadBalanceHosts=false&loginTimeout=0&logServerErrorDetail=true&logUnclosedConnections=false&preferQueryMode=extended&preparedStatementCacheQueries=256&preparedStatementCacheSizeMiB=5&prepareThreshold=5&quoteReturningIdentifiers=true&readOnly=false&readOnlyMode=transaction&receiveBufferSize=-1&reWriteBatchedInserts=false&sendBufferSize=-1&socketTimeout=0&sspiServiceClass=POSTGRES&targetServerType=any&tcpKeepAlive=false&tcpNoDelay=false&unknownLength=2147483647&useSpnego=false&xmlFactoryFactory=
```

connectTimeout is 10 here.

### Additional information

docker-compose.yml
```yaml
version: '3'

services:
  postgresql:
      image: docker.io/bitnami/postgresql:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRESQL_DATABASE: keycloak
        POSTGRESQL_USERNAME: keycloak
        POSTGRESQL_PASSWORD: hidden

  keycloak:
      build: keycloak
      environment:
        # database
        KEYCLOAK_DATABASE_HOST: postgresql
        KEYCLOAK_DATABASE_SCHEMA: public
        KEYCLOAK_DATABASE_PORT: 5432
        KEYCLOAK_DATABASE_NAME: keycloak
        KEYCLOAK_DATABASE_USER: keycloak
        KEYCLOAK_DATABASE_PASSWORD: hidden
        KEYCLOAK_JDBC_PARAMS: connectTimeout=300
        # administration
        KEYCLOAK_CREATE_ADMIN_USER: true
        KEYCLOAK_ADMIN_USER: admin
        KEYCLOAK_ADMIN_PASSWORD: hidden
        KEYCLOAK_MANAGEMENT_USER: manager
        KEYCLOAK_MANAGEMENT_PASSWORD: hidden
        # keycloak
        KEYCLOAK_PRODUCTION: no
        KEYCLOAK_HTTP_PORT: 8080
        KEYCLOAK_BIND_ADDRESS: 0.0.0.0
        KEYCLOAK_EXTRA_ARGS: >
          --features=scripts,declarative-user-profile
        KEYCLOAK_HTTP_RELATIVE_PATH: /
        # tls
        KEYCLOAK_ENABLE_TLS: true
        KEYCLOAK_TLS_KEYSTORE_FILE: /opt/bitnami/keycloak.keystore.jks
        KEYCLOAK_TLS_KEYSTORE_PASSWORD: hidden
        KEYCLOAK_TLS_TRUSTSTORE_FILE: /opt/bitnami/keycloak.truststore.jks
        KEYCLOAK_TLS_TRUSTSTORE_PASSWORD: hidden
      volumes: 
        - ./providers:/opt/bitnami/keycloak/providers
      ports:
        - "8080:8080"
        - "8443:8443"
      depends_on:
        - postgresql

volumes:
  postgres_data:
      driver: local
```

Thanks for your advice

UPDATE1 2022-07-06: Add docker-compose.yml
